setwd("D:/kaggle_redhat/Statistics")
mydata=read.csv("SalesSalary.csv", header=TRUE)
head(mydata)
attach(mydata)
Box1=boxplot(Salary~Position, main="Comparative Salary for Position", ylab="Salary", col=c("Red", "Green"))
Box2=boxplot(Salary~Experience, main="Comparative Salary for Experience", ylab="Salary", col=c("Red", "Green", "Pink"))
Model1=lm(Salary~Position)
summary(Model1)
anova(Model1)
Model2=lm(Salary~Experience)
summary(Model2)
anova(Model2)
Model3=lm(Salary~Position+Experience)
summary(Model3)
anova(Model3)
Model4=lm(Salary~Position+Experience+Position*Experience)
summary(Model4)
anova(Model4)
colors=c(rep("Green",1), rep("Red", 1), rep("Orange", 1))
interaction.plot(Position, Experience, Salary, col=colors)
Model5=aov(Salary~Position*Experience)
summary(Model5)
Model6=aov(Salary~Position+Experience+Position*Experience)
summary(Model6)
Colors=c(rep("Green",2), rep("Red", 2), rep("Pink", 2))
boxplot(Salary~Position*Experience, main="Comparative Picture of Salary for Position and Experience", ylab="Salary", col=Colors)
 
gapCleaned=read.csv("gapC.csv",header = T,na.strings = c("",NA))
head(gapCleaned)
means<- round(tapply(gapCleaned$breastcancer, gapCleaned$continent, mean), digits=2)  # note that I round values to just 2 decimal places
means

